### ISSUE TITLE
Adding Analysis Notes?

### ISSUE THREAD

**Issue by JamesPHoughton** [soleil-alpin/Transcriptions#4]
Hey David,

I'm enjoying using the tool, and it would be fantastic to be able to annotate the transcribed text with analysis that is separate from the text of the transcript itself, akin to how you can add a sticky note to a pdf, or similar. (A user could of course, take the transcribed text and annotate it elsewhere, but its nice to have it tied to the audio.) What do you think?

**Comment by davidhaselb** [comment]
Hello James,

glad that you like the app :) Thank you for your feature request. I actually thought about it already, but Transcriptions doesn´t support annotations (yet). At the moment the app gets some smaller improvements in user experience.

Kind regards,
David

**Comment by JanX2** [comment]
@JamesPHoughton The issue here is that the Cocoa text system does not allow this kind of customization of the engine that reads and writes RTF. We would have to write our own custom RTF subsystem. This would be a huge amount of work.

The RTF file format itself should support this AFAICT: 

https://en.wikipedia.org/wiki/Rich_Text_Format#Annotations
